export const GET_CAKES = 'GET_CAKES'
export const GET_CAKES_SUCCESS = 'GET_CAKES_SUCCESS'
export const GET_CAKES_FAILURE = 'GET_CAKES_FAILURE'

export const CREATE_CAKE = 'CREATE_CAKE'
export const CREATE_CAKE_SUCCESS = 'CREATE_CAKE_SUCCESS'
export const CREATE_CAKE_FAILURE = 'CREATE_CAKE_FAILURE'

export const SELECT_CAKE = 'SELECT_CAKE'
